#!/usr/bin/env zsh

# Install git netrc credential helper
printf "Installing git netrc credential helper.\\n"
curl --silent --show-error --create-dirs --output ~/bin/git-credential-netrc \
  https://raw.githubusercontent.com/git/git/master/contrib/credential/netrc/git-credential-netrc || \
  { printf "Unable to curl git-credential-netrc.\\n"; exit 1; }
chmod +x ~/bin/git-credential-netrc || \
  { printf "Unable to set execute bit on git-credential-netrc.\\n"; exit 1; }
printf "git-credential-netrc downloaded and execute bit set.\\n"
