#!/usr/bin/env bash

# Update submodules
pushd "$HOME" || { printf "Can not change to home directory."; exit 1; }
printf "Init submodules"
yadm submodule update --recursive --init
popd || { printf "Can not change to previous directory."; exit 1; }

curl_and_chmod(){
  local utility="${1}"
  local url="${2}"

  printf "Installing %s utility.\\n" "${utility}"
  curl --silent --show-error --create-dirs --output "${utility}" \
    "${url}" || { printf "Unable to curl %s.\\n" "${utility}"; exit 1; }
  chmod +x "${utility}" || \
    { printf "Unable to set execute bit on %s.\\n" "${utility}"; exit 1; }
  printf "%s downloaded and execute bit set.\\n" "${utility}"
}

# Install utilities to ~/bin
pushd ~/bin || { printf "Can not change to ~/bin."; exit 1; }

# Install git netrc credential helper
utility=git-credential-netrc
url=https://raw.githubusercontent.com/git/git/master/contrib/credential/netrc/"${utility}"
curl_and_chmod "${utility}" "${url}"

# Install diff-highlight git utility
utility=diff-highlight
url=https://raw.githubusercontent.com/git/git/fd99e2bda0ca6a361ef03c04d6d7fdc7a9c40b78/contrib/"${utility}/${utility}"
curl_and_chmod "${utility}" "${url}"

# Install minio commandline cli
utility=mc
url=https://dl.minio.io/client/"${utility}"/release/linux-amd64/"${utility}"
curl_and_chmod "${utility}" "${url}"
